[build]
watchPatterns = ["src/**", "messages/**", "prisma/**", "public/**", "next.config.mjs", "package.json", "server.js", "Dockerfile"]

[deploy]
preDeployCommand = "npx prisma migrate deploy"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
drainingSeconds = 10
